### ISSUE TITLE
Message: Invalid escape sequence

### ISSUE THREAD

**Issue by marco-mariotti** [mariottigenomicslab/selenoprofiles4#12]
From v4.5, python 3.12 we see messages when running selenoprofiles:

invalid escape sequence '\|'
invalid escape sequence '\|'
invalid escape sequence '\|'
invalid escape sequence '\w'
invalid escape sequence '\w'
invalid escape sequence '\|'
invalid escape sequence '\|'
invalid escape sequence '\|'
invalid escape sequence '\|'
invalid escape sequence '\|'

**Comment by marco-mariotti** [comment]
solved in 4.5.1

**Comment by jantmo** [comment]
Hi,
I just installed selenoprofiles using conda-forge using the following command

conda install -c mmariotti -c conda-forge  -c bioconda -c biobuilds selenoprofiles4

When running selenoprofiles I still see the invalid sequence message.
Perhaps a different issue, downloading the database doesn't work, nor does from the conda install or using docker.
I downloaded it manually from github and placed it in the corresponding path but I get the the database is locked.

Thank you so much 



`
$ selenoprofiles -h full

|         selenoprofiles v4.5.2          Host: deigo-login1.oist.jp   Date: Fri Mar 14 18:37:56 JST 2025
invalid escape sequence '\|'
invalid escape sequence '\|'
invalid escape sequence '\|'
invalid escape sequence '\w'
invalid escape sequence '\w'
invalid escape sequence '\|'
invalid escape sequence '\|'
Profile-based prediction of protein families in nucleotide sequences. Usage:

selenoprofiles  -o output_folder  -t target_file  -s "species name"  -p profile  [other options]
....

`

**Comment by maggiesudo** [comment]
Hi,  I am using v4.5.7 and I still see the invalid sequence message.

Do we need to be concerned with the warnings? The pipeline seems to work perfectly.

**Comment by marco-mariotti** [comment]
no worries, it's minor. but thanks for notifying

**Comment by marco-mariotti** [comment]
Fixed in 4.5.8
